Traceback (most recent call last):
  File "tools/oai-pmh-to-skos/link-ysa-allars.py", line 12, in <module>
    ysa.parse(sys.argv[1], format='turtle')
  File "/usr/lib/python2.6/site-packages/rdflib/graph.py", line 1039, in parse
    parser.parse(source, self, **args)
  File "/usr/lib/python2.6/site-packages/rdflib/plugins/parsers/notation3.py", line 1870, in parse
    p.loadStream(source.getByteStream())
  File "/usr/lib/python2.6/site-packages/rdflib/plugins/parsers/notation3.py", line 434, in loadStream
    return self.loadBuf(stream.read())    # Not ideal
  File "/usr/lib/python2.6/site-packages/rdflib/plugins/parsers/notation3.py", line 440, in loadBuf
    self.feed(buf)
  File "/usr/lib/python2.6/site-packages/rdflib/plugins/parsers/notation3.py", line 466, in feed
    i = self.directiveOrStatement(s, j)
  File "/usr/lib/python2.6/site-packages/rdflib/plugins/parsers/notation3.py", line 487, in directiveOrStatement
    j = self.statement(argstr, i)
  File "/usr/lib/python2.6/site-packages/rdflib/plugins/parsers/notation3.py", line 725, in statement
    j = self.property_list(argstr, i, r[0])
  File "/usr/lib/python2.6/site-packages/rdflib/plugins/parsers/notation3.py", line 1089, in property_list
    "objectList expected")
  File "/usr/lib/python2.6/site-packages/rdflib/plugins/parsers/notation3.py", line 1615, in BadSyntax
    raise BadSyntax(self._thisDoc, self.lines, argstr, i, msg)
rdflib.plugins.parsers.notation3.BadSyntax: at line 109253 of <>:
Bad syntax (objectList expected) at ^ in:
"... Ylähäme"@fi .

<http://www.yso.fi/onto/ysa/Y226190> a sko^s:Concept,
        ysa-meta:GeographicalConcept ;
    dc:sou..."
